image: node:22
stages:
  - build

build_job:
  stage: build
  script:
    - echo "first step"
    - echo "build stage running successfully"
    - node -v
    - echo "node version checked"
    - npm -v
    - echo "npm version checked"
    - npm install
    - npm run build
    - echo "last step"
    - echo "this is the end of build stage"
