stages:
  - build

build_job:
  stage: build
  script:
    - echo "first step"
    - echo "build stage running successfully"
    - node -v
    - npm -v
    - echo "last step"
    - echo "this is the end of build stage"
